export * from './cache'
export * from './favoritePokemon.mutation'
export * from './fragments'
export * from './getPokemonbyId.query'
export * from './getPokemonByName.query'
export * from './getPokemons.query'
export * from './getPokemonTypes.query'
export * from './unFavoritePokemon.mutation'
